---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: rhel7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

- include_tasks: rhel8.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int > 7

- name: get activemq configuration
  get_url:
    # yamllint disable-line rule:line-length
    url: https://raw.githubusercontent.com/opencast/opencast/r/{{ opencast_version_major }}.x/docs/scripts/activemq/activemq.xml
    dest: /etc/activemq/activemq.xml
    mode: '0644'
  notify: restart activemq

- name: start and enable activemq
  service:
    name: activemq
    enabled: true
